// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: apiconfig.proto

package ateconfigpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The unified configuration object for ate-api-server.
//
// Rules: If you include your configuration setting in the config file, it
// *must* be hot-reloadable using apiconfig.Loader.
type APIConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Authentication configuration for users calling the Substrate APIs.
	Authentication *APIClientAuthentication `protobuf:"bytes,1,opt,name=authentication,proto3" json:"authentication,omitempty"`
	Logging        *APILogging              `protobuf:"bytes,2,opt,name=logging,proto3" json:"logging,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *APIConfig) Reset() {
	*x = APIConfig{}
	mi := &file_apiconfig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIConfig) ProtoMessage() {}

func (x *APIConfig) ProtoReflect() protoreflect.Message {
	mi := &file_apiconfig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIConfig.ProtoReflect.Descriptor instead.
func (*APIConfig) Descriptor() ([]byte, []int) {
	return file_apiconfig_proto_rawDescGZIP(), []int{0}
}

func (x *APIConfig) GetAuthentication() *APIClientAuthentication {
	if x != nil {
		return x.Authentication
	}
	return nil
}

func (x *APIConfig) GetLogging() *APILogging {
	if x != nil {
		return x.Logging
	}
	return nil
}

type APIClientAuthentication struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TrustedJwtIssuers []*TrustedJWTIssuer    `protobuf:"bytes,1,rep,name=trusted_jwt_issuers,json=trustedJwtIssuers,proto3" json:"trusted_jwt_issuers,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *APIClientAuthentication) Reset() {
	*x = APIClientAuthentication{}
	mi := &file_apiconfig_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIClientAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIClientAuthentication) ProtoMessage() {}

func (x *APIClientAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_apiconfig_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIClientAuthentication.ProtoReflect.Descriptor instead.
func (*APIClientAuthentication) Descriptor() ([]byte, []int) {
	return file_apiconfig_proto_rawDescGZIP(), []int{1}
}

func (x *APIClientAuthentication) GetTrustedJwtIssuers() []*TrustedJWTIssuer {
	if x != nil {
		return x.TrustedJwtIssuers
	}
	return nil
}

type TrustedJWTIssuer struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Name                     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TrustedIssuer            string                 `protobuf:"bytes,2,opt,name=trusted_issuer,json=trustedIssuer,proto3" json:"trusted_issuer,omitempty"`
	RequiredAudiences        []string               `protobuf:"bytes,3,rep,name=required_audiences,json=requiredAudiences,proto3" json:"required_audiences,omitempty"`
	CertificateAuthorityFile string                 `protobuf:"bytes,4,opt,name=certificate_authority_file,json=certificateAuthorityFile,proto3" json:"certificate_authority_file,omitempty"`
	DiscoveryTokenFile       string                 `protobuf:"bytes,5,opt,name=discovery_token_file,json=discoveryTokenFile,proto3" json:"discovery_token_file,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TrustedJWTIssuer) Reset() {
	*x = TrustedJWTIssuer{}
	mi := &file_apiconfig_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustedJWTIssuer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustedJWTIssuer) ProtoMessage() {}

func (x *TrustedJWTIssuer) ProtoReflect() protoreflect.Message {
	mi := &file_apiconfig_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustedJWTIssuer.ProtoReflect.Descriptor instead.
func (*TrustedJWTIssuer) Descriptor() ([]byte, []int) {
	return file_apiconfig_proto_rawDescGZIP(), []int{2}
}

func (x *TrustedJWTIssuer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TrustedJWTIssuer) GetTrustedIssuer() string {
	if x != nil {
		return x.TrustedIssuer
	}
	return ""
}

func (x *TrustedJWTIssuer) GetRequiredAudiences() []string {
	if x != nil {
		return x.RequiredAudiences
	}
	return nil
}

func (x *TrustedJWTIssuer) GetCertificateAuthorityFile() string {
	if x != nil {
		return x.CertificateAuthorityFile
	}
	return ""
}

func (x *TrustedJWTIssuer) GetDiscoveryTokenFile() string {
	if x != nil {
		return x.DiscoveryTokenFile
	}
	return ""
}

type APILogging struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// debug, info, warn, or error
	Level         string `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APILogging) Reset() {
	*x = APILogging{}
	mi := &file_apiconfig_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APILogging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APILogging) ProtoMessage() {}

func (x *APILogging) ProtoReflect() protoreflect.Message {
	mi := &file_apiconfig_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APILogging.ProtoReflect.Descriptor instead.
func (*APILogging) Descriptor() ([]byte, []int) {
	return file_apiconfig_proto_rawDescGZIP(), []int{3}
}

func (x *APILogging) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

var File_apiconfig_proto protoreflect.FileDescriptor

const file_apiconfig_proto_rawDesc = "" +
	"\n" +
	"\x0fapiconfig.proto\x12\vateconfigpb\"\x8c\x01\n" +
	"\tAPIConfig\x12L\n" +
	"\x0eauthentication\x18\x01 \x01(\v2$.ateconfigpb.APIClientAuthenticationR\x0eauthentication\x121\n" +
	"\alogging\x18\x02 \x01(\v2\x17.ateconfigpb.APILoggingR\alogging\"h\n" +
	"\x17APIClientAuthentication\x12M\n" +
	"\x13trusted_jwt_issuers\x18\x01 \x03(\v2\x1d.ateconfigpb.TrustedJWTIssuerR\x11trustedJwtIssuers\"\xec\x01\n" +
	"\x10TrustedJWTIssuer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0etrusted_issuer\x18\x02 \x01(\tR\rtrustedIssuer\x12-\n" +
	"\x12required_audiences\x18\x03 \x03(\tR\x11requiredAudiences\x12<\n" +
	"\x1acertificate_authority_file\x18\x04 \x01(\tR\x18certificateAuthorityFile\x120\n" +
	"\x14discovery_token_file\x18\x05 \x01(\tR\x12discoveryTokenFile\"\"\n" +
	"\n" +
	"APILogging\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05levelB2Z0github.com/agent-substrate/pkg/proto/ateconfigpbb\x06proto3"

var (
	file_apiconfig_proto_rawDescOnce sync.Once
	file_apiconfig_proto_rawDescData []byte
)

func file_apiconfig_proto_rawDescGZIP() []byte {
	file_apiconfig_proto_rawDescOnce.Do(func() {
		file_apiconfig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apiconfig_proto_rawDesc), len(file_apiconfig_proto_rawDesc)))
	})
	return file_apiconfig_proto_rawDescData
}

var file_apiconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_apiconfig_proto_goTypes = []any{
	(*APIConfig)(nil),               // 0: ateconfigpb.APIConfig
	(*APIClientAuthentication)(nil), // 1: ateconfigpb.APIClientAuthentication
	(*TrustedJWTIssuer)(nil),        // 2: ateconfigpb.TrustedJWTIssuer
	(*APILogging)(nil),              // 3: ateconfigpb.APILogging
}
var file_apiconfig_proto_depIdxs = []int32{
	1, // 0: ateconfigpb.APIConfig.authentication:type_name -> ateconfigpb.APIClientAuthentication
	3, // 1: ateconfigpb.APIConfig.logging:type_name -> ateconfigpb.APILogging
	2, // 2: ateconfigpb.APIClientAuthentication.trusted_jwt_issuers:type_name -> ateconfigpb.TrustedJWTIssuer
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_apiconfig_proto_init() }
func file_apiconfig_proto_init() {
	if File_apiconfig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apiconfig_proto_rawDesc), len(file_apiconfig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apiconfig_proto_goTypes,
		DependencyIndexes: file_apiconfig_proto_depIdxs,
		MessageInfos:      file_apiconfig_proto_msgTypes,
	}.Build()
	File_apiconfig_proto = out.File
	file_apiconfig_proto_goTypes = nil
	file_apiconfig_proto_depIdxs = nil
}
